packages:
  - apps/*
  - packages/*
  - docs

catalog:
  '@astrojs/react': ^4.3.0
  date-fns: ^4.1.0
  react-day-picker: ^9.7.0

catalogs:
  cli:
    '@antfu/eslint-config': ^4.16.1
    eslint: ^9.29.0
    lint-staged: ^16.1.2
    simple-git-hooks: ^2.13.0

  styles:
    '@radix-ui/react-slot': ^1.2.3
    '@tailwindcss/vite': ^4.1.11
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    lucide-react: ^0.525.0
    tailwind-merge: ^3.3.1
    tailwindcss: ^4.1.11
    tw-animate-css: ^1.3.4

  types:
    '@types/react': ^19.1.8
    '@types/react-dom': ^19.1.6

  utils:
    fs-extra: ^11.3.0
    globals: ^16.2.0
    yaml: ^2.8.0

  web:
    astro: ^5.11.0
    react: ^19.1.0
    react-dom: ^19.1.0

onlyBuiltDependencies:
  - simple-git-hooks
