packages:
  - apps/*
  - packages/*
  - docs

catalog:

catalogs:
  cli:
    '@antfu/eslint-config': ^4.16.1
    eslint: ^9.29.0
    lint-staged: ^16.1.2
    simple-git-hooks: ^2.13.0

  styles:
    '@unocss/reset': ^66.3.2
    unocss: ^66.3.2

  types:
    '@types/node': ^24.0.10
    '@types/react': ^19.1.8
    '@types/react-dom': ^19.1.6

  utils:
    fs-extra: ^11.3.0
    yaml: ^2.8.0

  web:
    '@astrojs/react': ^4.3.0
    astro: ^5.11.0
    react: ^19.1.0
    react-dom: ^19.1.0

onlyBuiltDependencies:
  - simple-git-hooks
